---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      community.kubernetes.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        #kubeconfig: ~/.kube/config
    - name: Deploy nginx app
      community.kubernetes.k8s:
        src: ~/ansible/nginx-config.yaml
        state: present
        #kubeconfig: ~/.kube/config
        namespace: my-app     
