---
plugin: aws_ec2
regions:
  - ap-northeast-1
#filters:
  # All instances with their `Environment` tag set to `dev`
  #tag:Environment: dev
keyed_groups:
  - key: tags
    prefix: tag
  - key: instance_type
    prefix: instance_type
